[package]
name = "libnv-sys"
version = "0.1.3"
authors = ["Andrey Cherkashin <with.out@me.com>"]
links = "libnv"
build = "build.rs"
categories = ["external-ffi-bindings"]
license = "BSD-2-Clause"
description = "FFI bindings to libnv."
[lib]
name = "libnv_sys"

[dependencies]
libc = "0.2"
